# Gleidson Vinícius Gomes Barbosa - 6331

# Adicionando as bibliotecas

In [2]:
## Adicionando as bibliotecas
import numpy as np
import matplotlib as mp

# 1-A) + 2-A)B)C)

In [87]:
a = np.random.randint(0,256,100)
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[ 86 158 249  79 118 224 184 254  50 158 117  41 238  47 110 128 145 169
 107 236 254  82  26 145  24   3 158  84  11  65  33  98 129 130 137 133
  32   2   8 141  44 246 229  65 122 182  52  98 226  41 236  97  65 232
 192 194  95 138  50  55 158  20  20 136 222 175 180 193 123  49 225 113
 252 246 160  66  54 162 141 147 244 132 145 243 145  79 166  96 246  93
 243 204  51  90 151 220 229 166   5 130]
1
(100,)
int32


# 1-B) + 2-A)B)C)

In [78]:
b = np.arange(64,129,2)
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[ 64  66  68  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98
 100 102 104 106 108 110 112 114 116 118 120 122 124 126 128]
1
(33,)
int32


# 1-C) + 2-A)B)C)

In [3]:
c = np.arange(10,dtype=int)
print(c)
print(c.ndim)
print(c.shape)
print(c.dtype)

[0 1 2 3 4 5 6 7 8 9]
1
(10,)
int32


# 1-D) + 2-A)B)C)

In [97]:
d = np.arange(8,dtype=int) + np.arange(10,dtype=int)[:, np.newaxis]
print(d)
print(d.ndim)
print(d.shape)
print(d.dtype)

[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]
 [ 8  9 10 11 12 13 14 15]
 [ 9 10 11 12 13 14 15 16]]
2
(10, 8)
int32


# 1-E) + 2-A)B)C)

In [82]:
e = np.ones((20,20))
print(e)
print(e.ndim)
print(e.shape)
print(e.dtype)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
2
(20, 20)
int32


# 1-F) + 2-A)B)C)

In [83]:
f = np.zeros((20,30))
print(f)
print(f.ndim)
print(f.shape)
print(f.dtype)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

# 1-G) + 2-A)B)C)

In [49]:
g = np.random.rand(32, 32)
print(g)
print(g.ndim)
print(g.shape)
print(g.dtype)

[[0.16420137 0.28813281 0.95573693 ... 0.05663184 0.00299362 0.33016747]
 [0.74726757 0.210687   0.69773289 ... 0.96158805 0.97136621 0.78749199]
 [0.14036951 0.09033351 0.93332912 ... 0.67354268 0.5666413  0.22225872]
 ...
 [0.45238909 0.3295747  0.85523023 ... 0.26791593 0.93961644 0.67115877]
 [0.69666249 0.16399301 0.45741894 ... 0.50316451 0.97731765 0.18365333]
 [0.14879481 0.83029073 0.59194226 ... 0.89546343 0.79938507 0.9962548 ]]
2
(32, 32)
float64


array([0.74726757, 0.210687  , 0.69773289, 0.85510716, 0.75244494,
       0.73684091, 0.11577759, 0.34320122, 0.69921837, 0.0663606 ,
       0.46629492, 0.78896936, 0.15009133, 0.17173864, 0.78642416,
       0.65159046, 0.772044  , 0.49644766, 0.16039305, 0.92774062,
       0.52985542, 0.21632258, 0.02725772, 0.86686182, 0.74910749,
       0.55041492, 0.47969287, 0.77368307, 0.56504849, 0.96158805,
       0.97136621, 0.78749199])

# 1-H) + 2-A)B)C)

In [26]:
h = np.random.rand(32, 32, 3)
print(h)
print(h.ndim)
print(h.shape)
print(h.dtype)

[[[0.78827873 0.68292598 0.41618575]
  [0.94508578 0.52645235 0.30306919]
  [0.31159501 0.38741731 0.7122338 ]
  ...
  [0.25696741 0.28356358 0.95746852]
  [0.07304846 0.5558574  0.86489297]
  [0.1660898  0.56084451 0.38765333]]

 [[0.65390842 0.73975868 0.79378074]
  [0.30403664 0.35139395 0.67038937]
  [0.59881465 0.88060755 0.96900812]
  ...
  [0.65572494 0.94584418 0.52590691]
  [0.38465593 0.09733361 0.11870913]
  [0.70691798 0.30115166 0.08871646]]

 [[0.53862079 0.41695835 0.6293515 ]
  [0.78220984 0.50725015 0.14489506]
  [0.13472184 0.15060611 0.06478766]
  ...
  [0.23797304 0.45619277 0.72195733]
  [0.64777306 0.3109114  0.8008694 ]
  [0.03757917 0.53461609 0.02235622]]

 ...

 [[0.52804227 0.99797619 0.48311873]
  [0.86101517 0.78290191 0.3130876 ]
  [0.71586798 0.56995675 0.79771534]
  ...
  [0.68799825 0.2486285  0.5605657 ]
  [0.76593002 0.18497725 0.38530265]
  [0.73492279 0.99495994 0.431595  ]]

 [[0.05249968 0.64687783 0.61776966]
  [0.4252474  0.5040846  0.04631459]


# 3-A)

In [101]:
print(g[10])

[133 125  12  35 254 241  75  96 140 175 206 227 145  65 205 185 123   9
 235  81   0  79 219  88  18  12   5 251 103  67 134  96]


# 3-B)

In [114]:
print(g[1::2, 5]) 

[ 77  70   7 158  83 153  57 239 117 110 183  25 204  75  79 190]


# 3-C)

In [12]:
print(g[0:10,22:])

[[0.25183586 0.6751387  0.12381363 0.14037909 0.95309466 0.79403923
  0.26579536 0.23937614 0.78380652 0.22925924]
 [0.98771535 0.4164664  0.45523941 0.37132673 0.57630632 0.83462439
  0.90817471 0.94268515 0.76044726 0.67792851]
 [0.96917832 0.15127939 0.74134686 0.69737974 0.3975109  0.25123747
  0.91485491 0.82511966 0.37964185 0.83253813]
 [0.79656518 0.97104978 0.25125445 0.03559559 0.50599462 0.10150595
  0.98019096 0.85000258 0.21420745 0.29877473]
 [0.44777262 0.89732398 0.6618125  0.5074166  0.55650639 0.48648452
  0.83954057 0.80168107 0.14729837 0.86174858]
 [0.22121834 0.28572784 0.13276991 0.90144855 0.20596062 0.34111544
  0.98577618 0.01279349 0.96361145 0.58076277]
 [0.01175954 0.1884864  0.98429373 0.3308871  0.5594341  0.88418276
  0.53420172 0.7531908  0.09018122 0.22686989]
 [0.19910033 0.51308865 0.72680222 0.69315854 0.15352939 0.09363565
  0.33061919 0.35206929 0.83788091 0.238998  ]
 [0.28194217 0.48766634 0.37522285 0.28876601 0.43678195 0.78725484
  0.84341025

# 3-D)

In [13]:
print(g[22:,0:20])

[[0.59943644 0.75286476 0.44453314 0.83703662 0.76783385 0.22542516
  0.70696743 0.44944852 0.74524106 0.01680989 0.8879725  0.83554824
  0.41533568 0.99792036 0.53889307 0.55649475 0.67314604 0.75329502
  0.67052386 0.23464393]
 [0.4703037  0.1062466  0.05756917 0.05607023 0.27193191 0.1381597
  0.13039494 0.57050404 0.70273215 0.38120601 0.11552813 0.20200281
  0.74894909 0.69719666 0.99031675 0.15856422 0.89639126 0.68959113
  0.22291271 0.77343574]
 [0.02018603 0.31782857 0.63663733 0.74084923 0.57095659 0.52762531
  0.81890545 0.58070921 0.35902292 0.0978138  0.46707875 0.23449728
  0.07804541 0.95001191 0.43946711 0.33102242 0.28558768 0.87762134
  0.98894435 0.33545247]
 [0.85019188 0.22421422 0.01514034 0.57832373 0.55309673 0.85151469
  0.60758776 0.15415011 0.76095326 0.47800523 0.68533859 0.17728836
  0.59268145 0.0441332  0.36595084 0.8176083  0.85357528 0.51864769
  0.72500446 0.26130735]
 [0.4282949  0.96911628 0.75293608 0.72471612 0.24890042 0.58494028
  0.43861633 0.15

# 3-E)

In [32]:
g[0:, 0:16] = 0 #atribuindo zero à metade da esquerda
e_3 = g #armazenando o resultado em outra variável
print(e_3)
print(np.may_share_memory(g, e_3)) #checando se é cópia nesse caso, ainda é uma visão
e_3 = np.copy(g)
print(e_3)
print(np.may_share_memory(g, e_3)) #checando novamente, agora é uma cópia

[[0.         0.         0.         ... 0.67703089 0.17965095 0.84648215]
 [0.         0.         0.         ... 0.81565726 0.5063963  0.62586683]
 [0.         0.         0.         ... 0.48507939 0.44958254 0.71810256]
 ...
 [0.         0.         0.         ... 0.73411004 0.06839925 0.12161176]
 [0.         0.         0.         ... 0.15592777 0.11044471 0.93633726]
 [0.         0.         0.         ... 0.27998025 0.74529797 0.3993862 ]]
True
[[0.         0.         0.         ... 0.67703089 0.17965095 0.84648215]
 [0.         0.         0.         ... 0.81565726 0.5063963  0.62586683]
 [0.         0.         0.         ... 0.48507939 0.44958254 0.71810256]
 ...
 [0.         0.         0.         ... 0.73411004 0.06839925 0.12161176]
 [0.         0.         0.         ... 0.15592777 0.11044471 0.93633726]
 [0.         0.         0.         ... 0.27998025 0.74529797 0.3993862 ]]
False


# 3-F)

In [15]:
e_3_1 = np.copy(g[0:8, 0:8])#Arranjo 1
e_3_2 = np.copy(g[0:8, 8:16])#Arranjo 2
e_3_3 = np.copy(g[0:8, 16:24])#Arranjo 3
e_3_4 = np.copy(g[0:8, 24:32])#Arranjo 4
e_3_5 = np.copy(g[8:16, 0:8])#Arranjo 5
e_3_6 = np.copy(g[8:16, 8:16])#Arranjo 6
e_3_7 = np.copy(g[8:16, 16:24])#Arranjo 7
e_3_8 = np.copy(g[8:16, 24:32])#Arranjo 8
e_3_9 = np.copy(g[16:24, 0:8])#Arranjo 9
e_3_10 = np.copy(g[16:24, 8:16])#Arranjo 10
e_3_11 = np.copy(g[16:24, 16:24])#Arranjo 11
e_3_12 = np.copy(g[16:24, 24:32])#Arranjo 12
e_3_13 = np.copy(g[24:32, 0:8])#Arranjo 13
e_3_14 = np.copy(g[24:32, 8:16])#Arranjo 14
e_3_15 = np.copy(g[24:32, 16:24])#Arranjo 15
e_3_16 = np.copy(g[24:32, 24:32])#Arranjo 16

# 4-A)

In [36]:
a_4 = g > 0 #criando uma mascara
extract = g[a_4] #extraindo apenas valores maiores que 0.3
print(extract)#imprimindo valores maiores que 0.3

[0.08275544 0.25626732 0.83865233 0.51087866 0.38457391 0.95900214
 0.35309019 0.33656729 0.99887649 0.17558691 0.73008886 0.62845764
 0.73141939 0.67703089 0.17965095 0.84648215 0.89504548 0.65058347
 0.34519893 0.53684038 0.76799904 0.40169193 0.02607535 0.4722533
 0.12753128 0.10698858 0.31825722 0.1851163  0.92343673 0.81565726
 0.5063963  0.62586683 0.67055594 0.6466577  0.64352854 0.07467468
 0.84397552 0.6209763  0.073708   0.69701526 0.664311   0.29027864
 0.88841278 0.81075013 0.81185145 0.48507939 0.44958254 0.71810256
 0.06610063 0.12823997 0.50177576 0.78892901 0.61507043 0.01196227
 0.57036516 0.94930306 0.7717978  0.38741118 0.9325497  0.8925505
 0.59107922 0.24867077 0.26326724 0.13192885 0.81667445 0.17242428
 0.45485388 0.52968141 0.99095131 0.33710032 0.65724842 0.26106524
 0.48861174 0.29030622 0.97789718 0.26893189 0.76797163 0.89844301
 0.54765395 0.9318378  0.34203892 0.44475055 0.17399829 0.4195178
 0.28785723 0.09517272 0.93842763 0.58463813 0.10095787 0.9373174

# 4-B)

In [37]:
b_4 = g <= 0.3 #Criando o arranjo
b_4 # imprimindo para checar

array([[ True,  True,  True, ..., False,  True, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ...,  True,  True, False],
       [ True,  True,  True, ...,  True, False, False]])

# 4-C)

In [40]:
g[(1, 1, 2, 2, 4, 4), (2, 4, 3, 5, 6, 8)] 

array([0.65055539, 0.58872477, 0.11584934, 0.13682676, 0.23960256,
       0.55482066])

# 4-D)

In [47]:
g[0:,(1, 3, 7, 10, 21, 29)] 

array([[0.67450141, 0.32473407, 0.13869347, 0.64446483, 0.36116048,
        0.07003209],
       [0.90263312, 0.79146977, 0.73307313, 0.57620599, 0.27656657,
        0.75380404],
       [0.33764779, 0.11584934, 0.1147456 , 0.66674558, 0.62395925,
        0.83932697],
       [0.65357524, 0.08007878, 0.11271132, 0.3217261 , 0.46482913,
        0.89728448],
       [0.07970774, 0.52556415, 0.09847208, 0.3781139 , 0.2007231 ,
        0.2633636 ],
       [0.94862205, 0.43439774, 0.819517  , 0.83696852, 0.55233967,
        0.85942263],
       [0.49282939, 0.60946842, 0.24752422, 0.05591736, 0.81367847,
        0.28278593],
       [0.2133044 , 0.10571863, 0.62132218, 0.75489046, 0.60589075,
        0.04541896],
       [0.77768283, 0.2914622 , 0.00277916, 0.83290518, 0.34444912,
        0.44444694],
       [0.30560593, 0.62892151, 0.57301097, 0.64801778, 0.82512636,
        0.14501484],
       [0.40098046, 0.67318377, 0.5745657 , 0.01246962, 0.90721789,
        0.63911436],
       [0.22281084, 0

# 5 Arranjos

In [54]:
a_5_I = np.random.rand(32, 32)#Criando um arranjo com valores aleatórios 32x32
print(a_5_I)
a_5_II = np.random.rand(32, 1)#Criando um arranjo com valores aleatórios 32x32
print(a_5_II)

[[0.88673291 0.6184248  0.42206617 ... 0.91636559 0.41302703 0.20735234]
 [0.85940416 0.73667895 0.38656195 ... 0.53026564 0.89887683 0.45477828]
 [0.7733243  0.33595346 0.06067633 ... 0.59267078 0.91943917 0.59346162]
 ...
 [0.7411443  0.72731686 0.43228568 ... 0.38139205 0.48634348 0.04645086]
 [0.0044842  0.66012452 0.81985641 ... 0.5290169  0.99117755 0.55254592]
 [0.71428742 0.99961459 0.13858499 ... 0.27027648 0.36980334 0.38181387]]
[[0.17414633]
 [0.76186284]
 [0.57616551]
 [0.66973892]
 [0.42701115]
 [0.84848659]
 [0.27917273]
 [0.71988128]
 [0.65200249]
 [0.66258771]
 [0.27451171]
 [0.33161892]
 [0.31712493]
 [0.75524779]
 [0.60916825]
 [0.29817207]
 [0.93443187]
 [0.50333885]
 [0.91617043]
 [0.02562035]
 [0.55212688]
 [0.41325663]
 [0.2832057 ]
 [0.35699754]
 [0.23694554]
 [0.87613075]
 [0.702339  ]
 [0.3833803 ]
 [0.23847271]
 [0.94287447]
 [0.14952647]
 [0.04299106]]


# 5-A)

In [61]:
soma_a = g+a_5_I#soma
soma_a

array([[1.05093428, 0.90655761, 1.3778031 , ..., 0.97299743, 0.41602065,
        0.53751982],
       [1.60667173, 0.94736594, 1.08429484, ..., 1.49185369, 1.87024304,
        1.24227027],
       [0.91369382, 0.42628697, 0.99400545, ..., 1.26621347, 1.48608046,
        0.81572035],
       ...,
       [1.19353339, 1.05689155, 1.28751592, ..., 0.64930798, 1.42595992,
        0.71760963],
       [0.70114669, 0.82411753, 1.27727535, ..., 1.03218141, 1.9684952 ,
        0.73619925],
       [0.86308223, 1.82990532, 0.73052724, ..., 1.16573991, 1.16918841,
        1.37806867]])

In [60]:
sub_a = g-a_5_I#subtração
sub_a

array([[-0.72253154, -0.33029199,  0.53367077, ..., -0.85973375,
        -0.41003341,  0.12281513],
       [-0.11213659, -0.52599195,  0.31117094, ...,  0.43132241,
         0.07248939,  0.33271371],
       [-0.63295479, -0.24561996,  0.87265279, ...,  0.0808719 ,
        -0.35279787, -0.3712029 ],
       ...,
       [-0.2887552 , -0.39774216,  0.42294455, ..., -0.11347612,
         0.45327296,  0.62470791],
       [ 0.69217828, -0.4961315 , -0.36243747, ..., -0.0258524 ,
        -0.0138599 , -0.3688926 ],
       [-0.56549262, -0.16932386,  0.45335727, ...,  0.62518694,
         0.42958172,  0.61444093]])

In [62]:
mult_a = g*a_5_I#multiplicação
mult_a

array([[0.14560276, 0.17818848, 0.40338422, ..., 0.05189547, 0.00123645,
        0.068461  ],
       [0.64220486, 0.15520867, 0.26971699, ..., 0.5098971 , 0.87313858,
        0.35813425],
       [0.10855116, 0.03034785, 0.05663098, ..., 0.39918907, 0.5209922 ,
        0.13190202],
       ...,
       [0.3352856 , 0.23970523, 0.36970379, ..., 0.102181  , 0.45697633,
        0.0311759 ],
       [0.00312398, 0.10825581, 0.37501785, ..., 0.26618253, 0.96869531,
        0.1014769 ],
       [0.10628226, 0.82997072, 0.08203431, ..., 0.24202271, 0.29561527,
        0.3803839 ]])

# 5-B)

In [68]:
soma_b = g+a_5_II#soma
soma_b

array([[0.3383477 , 0.46227914, 1.12988326, ..., 0.23077816, 0.17713995,
        0.5043138 ],
       [1.50913041, 0.97254984, 1.45959573, ..., 1.72345089, 1.73322906,
        1.54935483],
       [0.71653502, 0.66649901, 1.50949463, ..., 1.24970819, 1.1428068 ,
        0.79842423],
       ...,
       [1.39526357, 1.27244917, 1.79810471, ..., 1.2107904 , 1.88249092,
        1.61403324],
       [0.84618895, 0.31351948, 0.6069454 , ..., 0.65269097, 1.12684412,
        0.33317979],
       [0.19178587, 0.87328179, 0.63493332, ..., 0.93845449, 0.84237613,
        1.03924586]])

In [67]:
sub_b = g-a_5_II#subtração
sub_b

array([[-0.00994496,  0.11398648,  0.7815906 , ..., -0.11751449,
        -0.1711527 ,  0.15602114],
       [-0.01459527, -0.55117585, -0.06412995, ...,  0.19972521,
         0.20950337,  0.02562915],
       [-0.43579599, -0.485832  ,  0.35716362, ...,  0.09737718,
        -0.00952421, -0.35390678],
       ...,
       [-0.49048538, -0.61329978, -0.08764424, ..., -0.67495855,
        -0.00325803, -0.2717157 ],
       [ 0.54713602,  0.01446655,  0.30789247, ...,  0.35363804,
         0.82779119,  0.03412686],
       [ 0.10580375,  0.78729967,  0.54895119, ...,  0.85247236,
         0.756394  ,  0.95326374]])

In [66]:
mult_b = g*a_5_II#multiplicação
mult_b

array([[2.85950655e-02, 5.01772708e-02, 1.66438077e-01, ...,
        9.86222613e-03, 5.21328493e-04, 5.74974528e-02],
       [5.69315394e-01, 1.60514594e-01, 5.31576764e-01, ...,
        7.32598204e-01, 7.40047824e-01, 5.99960888e-01],
       [8.08760721e-02, 5.20470503e-02, 5.37752045e-01, ...,
        3.88072060e-01, 3.26479169e-01, 1.28057808e-01],
       ...,
       [4.26546130e-01, 3.10747569e-01, 8.06374757e-01, ...,
        2.52611089e-01, 8.85940360e-01, 6.32818471e-01],
       [1.04169479e-01, 2.45212956e-02, 6.83962370e-02, ...,
        7.52364101e-02, 1.46134854e-01, 2.74610331e-02],
       [6.39684685e-03, 3.56950805e-02, 2.54482264e-02, ...,
        3.84969240e-02, 3.43664132e-02, 4.28300523e-02]])

# 5-C)

In [69]:
soma_c = a_5_I+a_5_II#soma
soma_c

array([[1.06087924, 0.79257113, 0.59621249, ..., 1.09051192, 0.58717336,
        0.38149867],
       [1.621267  , 1.49854179, 1.14842479, ..., 1.29212848, 1.66073967,
        1.21664112],
       [1.34948981, 0.91211897, 0.63684183, ..., 1.16883629, 1.49560467,
        1.16962713],
       ...,
       [1.68401877, 1.67019133, 1.37516016, ..., 1.32426652, 1.42921795,
        0.98932533],
       [0.15401067, 0.80965098, 0.96938287, ..., 0.67854337, 1.14070401,
        0.70207239],
       [0.75727849, 1.04260565, 0.18157605, ..., 0.31326755, 0.41279441,
        0.42480493]])

In [70]:
sub_c = a_5_I-a_5_II#subtração
sub_c

array([[ 0.71258658,  0.44427847,  0.24791984, ...,  0.74221926,
         0.2388807 ,  0.03320602],
       [ 0.09754132, -0.0251839 , -0.37530089, ..., -0.2315972 ,
         0.13701398, -0.30708456],
       [ 0.1971588 , -0.24021204, -0.51548918, ...,  0.01650528,
         0.34327366,  0.01729612],
       ...,
       [-0.20173018, -0.21555762, -0.51058879, ..., -0.56148243,
        -0.45653099, -0.89642362],
       [-0.14504226,  0.51059805,  0.67032994, ...,  0.37949044,
         0.84165108,  0.40301946],
       [ 0.67129636,  0.95662353,  0.09559393, ...,  0.22728542,
         0.32681228,  0.33882281]])

In [71]:
mult_c = a_5_I*a_5_II#multiplicação
mult_c

array([[1.54421280e-01, 1.07696408e-01, 7.35012728e-02, ...,
        1.59581702e-01, 7.19271406e-02, 3.61096494e-02],
       [6.54748097e-01, 5.61248317e-01, 2.94507185e-01, ...,
        4.03989689e-01, 6.84820854e-01, 3.46478673e-01],
       [4.45562788e-01, 1.93564797e-01, 3.49596071e-02, ...,
        3.41476462e-01, 5.29749132e-01, 3.41932117e-01],
       ...,
       [6.98806039e-01, 6.85768499e-01, 4.07591137e-01, ...,
        3.59604827e-01, 4.58560853e-01, 4.37973285e-02],
       [6.70507207e-04, 9.87060857e-02, 1.22590231e-01, ...,
        7.91020275e-02, 1.48207275e-01, 8.26202391e-02],
       [3.07079752e-02, 4.29744931e-02, 5.95791587e-03, ...,
        1.16194732e-02, 1.58982386e-02, 1.64145839e-02]])

# 5-D)

In [74]:
soma_d = g+42#soma
soma_d

array([[42.16420137, 42.28813281, 42.95573693, ..., 42.05663184,
        42.00299362, 42.33016747],
       [42.74726757, 42.210687  , 42.69773289, ..., 42.96158805,
        42.97136621, 42.78749199],
       [42.14036951, 42.09033351, 42.93332912, ..., 42.67354268,
        42.5666413 , 42.22225872],
       ...,
       [42.45238909, 42.3295747 , 42.85523023, ..., 42.26791593,
        42.93961644, 42.67115877],
       [42.69666249, 42.16399301, 42.45741894, ..., 42.50316451,
        42.97731765, 42.18365333],
       [42.14879481, 42.83029073, 42.59194226, ..., 42.89546343,
        42.79938507, 42.9962548 ]])

In [73]:
sub_d = g-42#subtração
sub_d

array([[-41.83579863, -41.71186719, -41.04426307, ..., -41.94336816,
        -41.99700638, -41.66983253],
       [-41.25273243, -41.789313  , -41.30226711, ..., -41.03841195,
        -41.02863379, -41.21250801],
       [-41.85963049, -41.90966649, -41.06667088, ..., -41.32645732,
        -41.4333587 , -41.77774128],
       ...,
       [-41.54761091, -41.6704253 , -41.14476977, ..., -41.73208407,
        -41.06038356, -41.32884123],
       [-41.30333751, -41.83600699, -41.54258106, ..., -41.49683549,
        -41.02268235, -41.81634667],
       [-41.85120519, -41.16970927, -41.40805774, ..., -41.10453657,
        -41.20061493, -41.0037452 ]])

In [75]:
mult_d = g*42#multiplicação
mult_d

array([[ 6.89645751, 12.10157804, 40.14095116, ...,  2.37853708,
         0.12573218, 13.86703382],
       [31.38523788,  8.84885384, 29.30478143, ..., 40.38669805,
        40.79738092, 33.07466367],
       [ 5.8955196 ,  3.79400726, 39.19982313, ..., 28.28879269,
        23.79893447,  9.33486626],
       ...,
       [19.00034198, 13.84213727, 35.91966984, ..., 11.25246895,
        39.46389062, 28.18866831],
       [29.25982445,  6.88770654, 19.2115954 , ..., 21.13290925,
        41.04734135,  7.7134398 ],
       [ 6.24938191, 34.87221057, 24.86157473, ..., 37.60946389,
        33.57417273, 41.84270164]])

# 5-E)

In [78]:
soma_e = a_5_II+42#soma
soma_e

array([[42.17414633],
       [42.76186284],
       [42.57616551],
       [42.66973892],
       [42.42701115],
       [42.84848659],
       [42.27917273],
       [42.71988128],
       [42.65200249],
       [42.66258771],
       [42.27451171],
       [42.33161892],
       [42.31712493],
       [42.75524779],
       [42.60916825],
       [42.29817207],
       [42.93443187],
       [42.50333885],
       [42.91617043],
       [42.02562035],
       [42.55212688],
       [42.41325663],
       [42.2832057 ],
       [42.35699754],
       [42.23694554],
       [42.87613075],
       [42.702339  ],
       [42.3833803 ],
       [42.23847271],
       [42.94287447],
       [42.14952647],
       [42.04299106]])

In [77]:
sub_e = a_5_II-42#subtração
sub_e

array([[-41.82585367],
       [-41.23813716],
       [-41.42383449],
       [-41.33026108],
       [-41.57298885],
       [-41.15151341],
       [-41.72082727],
       [-41.28011872],
       [-41.34799751],
       [-41.33741229],
       [-41.72548829],
       [-41.66838108],
       [-41.68287507],
       [-41.24475221],
       [-41.39083175],
       [-41.70182793],
       [-41.06556813],
       [-41.49666115],
       [-41.08382957],
       [-41.97437965],
       [-41.44787312],
       [-41.58674337],
       [-41.7167943 ],
       [-41.64300246],
       [-41.76305446],
       [-41.12386925],
       [-41.297661  ],
       [-41.6166197 ],
       [-41.76152729],
       [-41.05712553],
       [-41.85047353],
       [-41.95700894]])

In [79]:
mult_e = a_5_II*42#multiplicação
mult_e

array([[ 7.31414576],
       [31.9982394 ],
       [24.19895122],
       [28.12903445],
       [17.9344683 ],
       [35.63643658],
       [11.72525467],
       [30.23501371],
       [27.38410452],
       [27.82868373],
       [11.52949186],
       [13.92799483],
       [13.31924718],
       [31.72040718],
       [25.58506669],
       [12.52322686],
       [39.24613862],
       [21.14023165],
       [38.47915815],
       [ 1.0760546 ],
       [23.18932894],
       [17.35677852],
       [11.89463951],
       [14.99389662],
       [ 9.9517128 ],
       [36.7974914 ],
       [29.49823791],
       [16.10197245],
       [10.01585391],
       [39.6007279 ],
       [ 6.28011155],
       [ 1.80562462]])

# 5-F)

    Na letra A, são feitas as operações ponto a ponto ponto a ponto.
    Na letras B e C, o arranjo 2D(ii) é ajustado se replicando em todas as colunas e depois é feita a multiplicação ponto a ponto
    Na letras D e E, são realizadas as operações entre cada ponto e o escalar informado. 
    

# 6-A)

In [80]:
g.min()

0.0001732454003113837

In [81]:
g.max()

0.9992868509013646

In [82]:
g.mean()

0.5079290296141493

In [83]:
g.std()

0.2905509857543439

# 6-B)

In [84]:
g.min(axis=0)


array([0.01785263, 0.01725519, 0.01335092, 0.08424126, 0.0059657 ,
       0.02800319, 0.02069885, 0.03736087, 0.03717881, 0.0663606 ,
       0.00761195, 0.01104795, 0.02931664, 0.02366595, 0.0004184 ,
       0.00017325, 0.01195281, 0.11979256, 0.0058376 , 0.00047257,
       0.00103732, 0.07607418, 0.02725772, 0.0493417 , 0.01063237,
       0.01138015, 0.00662342, 0.02340648, 0.00088456, 0.02353512,
       0.00299362, 0.0045029 ])

In [85]:
g.max(axis=0)

array([0.94396786, 0.94261978, 0.95573693, 0.989979  , 0.94159293,
       0.93230382, 0.99200755, 0.99310812, 0.99684966, 0.98872965,
       0.97378533, 0.95420605, 0.99399433, 0.96020771, 0.96834371,
       0.98030014, 0.96753519, 0.99928685, 0.98104407, 0.98277889,
       0.99657655, 0.93743899, 0.94399672, 0.9813286 , 0.91912849,
       0.97750272, 0.98611783, 0.99043978, 0.98382646, 0.96629007,
       0.98812841, 0.9962548 ])

In [86]:
g.mean(axis=0)

array([0.4348967 , 0.44306292, 0.66240333, 0.54743876, 0.47622269,
       0.44256726, 0.53227978, 0.47039709, 0.48880765, 0.5484517 ,
       0.48691855, 0.40664559, 0.5661098 , 0.55395849, 0.43284499,
       0.51453893, 0.48441283, 0.56085755, 0.45696253, 0.55537229,
       0.58991679, 0.49038385, 0.49613579, 0.55324096, 0.46803347,
       0.57014203, 0.57532074, 0.4938553 , 0.54321038, 0.43035783,
       0.54704418, 0.43093818])

In [87]:
g.std(axis=0)

array([0.24933362, 0.29076894, 0.23263222, 0.28644659, 0.26024546,
       0.29540216, 0.28935526, 0.26442751, 0.27656481, 0.28211663,
       0.28049225, 0.30208   , 0.32760742, 0.26121272, 0.2607941 ,
       0.31769346, 0.268853  , 0.2783966 , 0.26264908, 0.32316401,
       0.31684577, 0.23240814, 0.27608396, 0.30159033, 0.31671601,
       0.30050186, 0.2332682 , 0.2668604 , 0.2881405 , 0.2753202 ,
       0.35598031, 0.29042561])

# 6-C)

In [89]:
g.min(axis=1)

array([0.00299362, 0.02725772, 0.00017325, 0.0539667 , 0.0058376 ,
       0.06657699, 0.01063237, 0.02022157, 0.0059657 , 0.01195281,
       0.07810646, 0.02640574, 0.0004184 , 0.02405886, 0.01885876,
       0.09214395, 0.02206563, 0.00662342, 0.03032854, 0.08424126,
       0.02366595, 0.00047257, 0.09212335, 0.01385034, 0.00761195,
       0.01725519, 0.0045029 , 0.01138015, 0.00103732, 0.02069885,
       0.00088456, 0.10204557])

In [90]:
g.max(axis=1)

array([0.97916864, 0.97136621, 0.95420605, 0.98107756, 0.99657655,
       0.93230382, 0.97344525, 0.89842988, 0.9390499 , 0.87983667,
       0.99043978, 0.97099256, 0.99684966, 0.99928685, 0.98277889,
       0.99178469, 0.99262051, 0.98872965, 0.97140737, 0.98030014,
       0.98611783, 0.98294849, 0.96224236, 0.98812841, 0.99204445,
       0.97378533, 0.99310812, 0.93250952, 0.97624717, 0.98382646,
       0.99399433, 0.9962548 ])

In [91]:
g.mean(axis=1)

array([0.51926828, 0.56484572, 0.5214857 , 0.47014125, 0.48343997,
       0.50172204, 0.52388253, 0.49504987, 0.48523162, 0.42008046,
       0.54749486, 0.531688  , 0.55247745, 0.48803143, 0.51834021,
       0.48576572, 0.48766162, 0.44816436, 0.57443072, 0.5879557 ,
       0.48213997, 0.40681886, 0.51801854, 0.5141884 , 0.52988622,
       0.52958736, 0.43833993, 0.47093737, 0.47324451, 0.5498692 ,
       0.49446055, 0.63908054])

In [92]:
g.std(axis=1)

array([0.31096994, 0.28443448, 0.28989363, 0.27958581, 0.31274543,
       0.27280489, 0.26335909, 0.238639  , 0.27196499, 0.28112666,
       0.2592647 , 0.2718884 , 0.29918784, 0.31235861, 0.26702101,
       0.27124902, 0.25823023, 0.28649608, 0.29516784, 0.27687998,
       0.32631745, 0.30287561, 0.26715005, 0.32935493, 0.27736642,
       0.32425021, 0.31785089, 0.26640476, 0.26038443, 0.29411523,
       0.31765986, 0.25371377])